cmake_minimum_required(VERSION 3.22)

target_include_directories(${TARGET} PUBLIC
    ${CMAKE_CURRENT_LIST_DIR}/
    ${CMAKE_CURRENT_LIST_DIR}/SEGGER
    ${CMAKE_CURRENT_LIST_DIR}/CONFIG
    ${CMAKE_CURRENT_LIST_DIR}/Sample/FreeRTOSV10.4
)

target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/SEGGER/SEGGER_SYSVIEW.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/SEGGER/SEGGER_RTT.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/SEGGER/SEGGER_RTT_printf.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/Sample/FreeRTOSV10.4/SEGGER_SYSVIEW_FreeRTOS.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/Sample/FreeRTOSV10.4/Config/Cortex-M/SEGGER_SYSVIEW_Config_FreeRTOS.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/Sample/FreeRTOSV10.4/Config/Cortex-M/SEGGER_SYSVIEW_Config_FreeRTOS.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/SEGGER/Syscalls/SEGGER_RTT_Syscalls_GCC.c)
target_sources(${TARGET} PRIVATE ${CMAKE_CURRENT_LIST_DIR}/SEGGER/SEGGER_RTT_ASM_ARMv7M.S)
