#ifndef BUTTON_HARDWARE_SPECIFIC_H_
#define BUTTON_HARDWARE_SPECIFIC_H_

typedef enum
{
    BUTTON_CHANNEL_A,
    BUTTON_CHANNEL_B,

    BUTTON_CHANNEL_1,
    BUTTON_CHANNEL_2,
    BUTTON_CHANNEL_3,
    BUTTON_CHANNEL_4,
    BUTTON_CHANNEL_5,
    BUTTON_CHANNEL_6,
    BUTTON_CHANNEL_7,
    BUTTON_CHANNEL_8,
    BUTTON_CHANNEL_9,
    BUTTON_CHANNEL_10,
    BUTTON_CHANNEL_11,
    BUTTON_CHANNEL_12,
    BUTTON_CHANNEL_13,
    BUTTON_CHANNEL_14,
    BUTTON_CHANNEL_15,
    BUTTON_CHANNEL_16,

    BUTTON_CHANNEL_COUNT,
    BUTTON_CHANNEL_UNDEFINED,
} Button_channel_E;

#endif /* BUTTON_HARDWARE_SPECIFIC_H_ */
