#ifndef LEDSHARDWARE_SPECIFIC_H_
#define LEDS_HARDWARE_SPECIFIC_H_

typedef enum
{
    LED_CHANNEL_BLINKY,
    LED_CHANNEL_BUTTON_1,
    LED_CHANNEL_BUTTON_2,
    LED_CHANNEL_BUTTON_3,
    LED_CHANNEL_BUTTON_4,
    LED_CHANNEL_BUTTON_5,
    LED_CHANNEL_BUTTON_6,
    LED_CHANNEL_BUTTON_7,
    LED_CHANNEL_BUTTON_8,
    LED_CHANNEL_BUTTON_9,
    LED_CHANNEL_BUTTON_10,
    LED_CHANNEL_BUTTON_11,
    LED_CHANNEL_BUTTON_12,
    LED_CHANNEL_BUTTON_13,
    LED_CHANNEL_BUTTON_14,
    LED_CHANNEL_BUTTON_15,
    LED_CHANNEL_BUTTON_16,

    LED_CHANNEL_COUNT,
} LED_channel_E;

#endif /* LEDS_HARDWARE_SPECIFIC_H_ */
